### ISSUE TITLE
python build/install stage with the following message (requires libffi)

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#1233]
Just tried installing ASGS in WSL2 (Ubuntu). It ran until it failed at the python build/install stage with the following message: 
```
Collecting netCDF4
  Downloading netCDF4-1.6.5.tar.gz (764 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 765.0/765.0 kB 4.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Package hdf5 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `hdf5.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'hdf5' found
      reading from setup.cfg...
      using /home/jason/asgs/opt/bin/nc-config...
      checking /home/jason/asgs/opt/include ...
      HDF5 library version: 1.12.2 headers found in /home/jason/asgs/opt/include
      Traceback (most recent call last):
        File "/home/jason/asgs/opt/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jason/asgs/opt/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jason/asgs/opt/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-jnwqtmb9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-jnwqtmb9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jnwqtmb9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 547, in <module>
        File "<string>", line 166, in getnetcdfvers
        File "/home/jason/asgs/opt/lib/python3.7/ctypes/__init__.py", line 7, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "cloud/general/t/netcdf4-bench.py", line 7, in <module>
    from numpy.random.mtrand import uniform
ModuleNotFoundError: No module named 'numpy'
post condition for "step for installing python 3 and required modules" FAILED, stopping. Please fix and rerun.
```

_Originally posted by @jasonfleming in https://github.com/StormSurgeLive/asgs/issues/1147#issuecomment-1781375017_

**Comment by wwlwpd** [comment]
@jasonfleming I just assume not try to install the netCDF library for python, I don't think we have anything left for it. Otherwise I'd have to install `libffi` as a seperate thing and I definitely don't want to do that. Thoughts?

**Comment by jasonfleming** [comment]
Dropping support for the netCDF4 python module wouldn't affect any of my scripts but URI does use this module (in the richamp-support repo).

**Comment by jasonfleming** [comment]
Containerization?

**Comment by wwlwpd** [comment]
These also require `numpy`:

```
cloud/general/t/netcdf4-bench.py
cloud/general/t/verify-python-modules.py
output/cellCenterCoords.py
output/kalpana.py
```

**Comment by wwlwpd** [comment]
> Containerization?

Maybe, let's discuss. We'd have to figure out how this fits in with everything else and how it magnifies general support issues.

**Comment by jasonfleming** [comment]
Conda?

**Comment by wwlwpd** [comment]
> Conda?

The problem is all the solutions require a privileged user (`root`) package to be installed. We can add this to the bootstrap for a personal machine, but this would not fly on institutional HPC clusters because it would require a sysadmin ticket.

**Comment by wwlwpd** [comment]
Tagged with `REMOVED-PYTHON`
